export const LOAD_USER_INFO_SUCCESS = 'LOAD_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const LOAD_EXERCISES_WEIGHTS_SUCCESS = 'LOAD_EXERCISES_WEIGHTS_SUCCESS';
export const SAVE_EXERCISE_WEIGHT_SUCCESS = 'SAVE_EXERCISE_WEIGHT_SUCCESS';
export const UPDATE_EXERCISE_WEIGHT_SUCCESS = 'UPDATE_EXERCISE_WEIGHT_SUCCESS';
